name: manage-azure-policy-77664448
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Deploy_Diag_Settings_for_EH_to_EH_eae69cbb-c55c-4a44-9dd2-21dff4be6aef/**'
#      - .github/workflows/manage-azure-policy-77664448.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_77664448}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Deploy_Diag_Settings_for_EH_to_EH_eae69cbb-c55c-4a44-9dd2-21dff4be6aef/**
