name: manage-azure-policy-233ce3f9
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/DeployDiagnosticSettingsforActivityLogtoEventHub2_074266a6-4aee-4e17-a78e-9ffd5cab9334/**'
#      - .github/workflows/manage-azure-policy-233ce3f9.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_233ce3f9}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/DeployDiagnosticSettingsforActivityLogtoEventHub2_074266a6-4aee-4e17-a78e-9ffd5cab9334/**
